### PR TITLE
use postgres 10.9 to match production

### PR DESCRIPTION
**Pull request by asmega**

### CODE REVIEW

**Comment by asmega** [comment]
I can change the development versions. Matching prod is best approach, otherwise the total opposite approach is to change the versions of everything to not match production, which wouldn't be very useful.

**Comment by asmega** [comment]
Sorry, I misunderstood the first bit. We're using whatever the latest postgres image is which is most likely not 10.9

**Comment by cob16** [comment]
> Sorry, I misunderstood the first bit. We're using whatever the latest postgres image is which is most likely not 10.9

Yeah so the other approach is to use a later version in dev to identify issues  eary.

**Comment by asmega** [comment]
If that's the thought process then why don't we run with the latest ruby, use rails 6 and unpin all gems to make sure we're ahead of the curve?

**Comment by tommotaylor** [comment]
I'll mediate this. I think you both have valid points but the code tells me that parity is the current strategy so lets go for that.

**Pull request merged**
